plugins:
  domniq_app_enabled:
    default: false
    client: true
  domniq_app_push_notifications_enabled:
    default: false
    client: true
    hidden: true
  domniq_app_video_thumbnails_enabled:
    default: true
    hidden: true
  domniq_app_telemetry_enabled:
    default: true
    hidden: true
